### ISSUE TITLE
Reproduce the React-Native build on a different machine

### ISSUE THREAD

**Issue by jritch** [Monsauce/Open-the-North#2]
In f9a5d3b and c9f3990 I've used the default .gitignore from https://github.com/facebook/react-native/blob/master/local-cli/templates/HelloWorld/_gitignore

To make sure I'm not ignoring any files that might be important for the build, it would be good to build and run the app from another machine (or a clone of the repo on my machine).

**Comment by jdpigeon** [comment]
I'll give this a shot

**Comment by Monsauce** [comment]
Thanks Dano!

**Comment by jdpigeon** [comment]
It works!

My machines:
Ubuntu 16 LTS x86
Nexus 5

My steps:
`git clone https://github.com/Monsauce/Open-the-North.git`
`cd Open-the-North/OpenTheNorthApp`
`yarn install`
`react-native start`
`react-native run-android`

**Comment by jritch** [comment]
Great! Thanks so much!

Now we know the "Hello World" app is functional for different developers.
